### ISSUE TITLE
Set Global as the default channel

### ISSUE THREAD

**Issue by freghar** [CntoDev/cba-settings-lock#1]
We used to have it in the old compositions:
https://github.com/CntoDev/compositions/blob/61d277c318/reference/Default%2520Modules%2520(Coop)/composition.sqe#L2809
```
			class Attribute2
			{
				property="ACE_ModuleMap_DefaultChannel";
				expression="_this setVariable ['DefaultChannel',_value,true];";
				class Value
				{
					class data
					{
						class type
						{
							type[]=
							{
								"SCALAR"
							};
						};
						value=0;
					};
				};
			};
```
but in our mod config file, it's `-1`:
```
force force ace_map_defaultChannel = -1;
```
(likely meaning "no change", thus Group being the default).

**Comment by Abuk007** [comment]
Implemented.

**Comment by Abuk007** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ACE3: Default chat channel on spawn to "Global"](https://trello.com/c/eWAWFiTb/504-ace3-default-chat-channel-on-spawn-to-global)
