### ISSUE TITLE
ACE NVG Sight Blur Settings

### ISSUE THREAD

**Issue by CNTODachi** [CntoDev/cba-settings-lock#2]
Please refer to this thread.

http://www.carpenoctem.co/forums/m/26081621/viewthread/31860315-ace-nvg-settings/post/last#last

NVG sight blur settings are far to punishing and not even in line with Dslyecxi's own video showing the blur effect.

Suggest we take it down to at least 0.2 or off completely due to our limitations in use of IR Lasers which would be the only other alternative.

**Comment by Abuk007** [comment]
Why wont we introduce lasers?
I think there was plenty of fixes already done to them so they don't impact FPS as much.

NVG are not meant for any medium to long range engagements, they never were.
If anything I'd be looking more towards reducing fog settings instead.

**Comment by CNTODachi** [comment]
I am not against lasers but I have not seen any indication that they have been fixed, he mentions some fixes in his video but not sure if they are vanilla or Shac Tacs we could test them.


I would probably create a new issue for Fog settings change but I agree fog is a weird setting that should be changed.

**Comment by Abuk007** [comment]
Entire NVG system is ShackTac's and was added to ACE completely, so for sure anything mentioned in video is in, alongside with any features/fixes from ACE team. I agree, lets talk fog first before tweaking other stuff.

**Comment by freghar** [comment]
(just FTR): That's technically not true, the ACE implementation is from scratch (like was the grenade throwing), inspired by Shacktac. For example the flashing white/black effect on muzzle flashes was left out.

**Comment by CNTODachi** [comment]
New Settings:

Can not create a Pull Request do not have the permission.

force force ace_nightvision_aimDownSightsBlur = 0.5;
force force ace_nightvision_disableNVGsWithSights = false;
force force ace_nightvision_effectScaling = 0.8;
force force ace_nightvision_fogScaling = 0.5;
force force ace_nightvision_noiseScaling = 0.7;

Keep this here for safe keeping.

**Comment by freghar** [comment]
@CNTODachi Create your own fork of the repo (top right, click the Fork button), clone that using your GH desktop and push changes to it. Then you can create a pull request from your repo to CntoDev.
