### ISSUE TITLE
ACRE2 Post-Mix Volume Setting

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/cba-settings-lock#34]
This issue report is inspired by something @freghar posted in Brainstorming: https://www.carpenoctem.co/forums/page/4/m/26081621/viewthread/33453813-jsrs/post/139541123#p139541123

In early 2015 we did a lot of testing regarding ACRE2 voice volume settings and determined that the following settings deliver the best results for most players over distance:

```
force force acre_sys_core_premixGlobalVolume = 1;
force force acre_sys_core_postmixGlobalVolume = 3;
```

For a long while, these settings were set to `force force` meaning enforced server-side. However, at some point, we removed the `force force`, ~~most likely due to complaints that this volume mix is too loud for some members depending on their individual audio setup. From that point onwards players were able to adjust the baseline settings on their own.~~
CORRECTION: this change was very likely a direct result of the ACRE2 mod update described below and thus was not intentional, found a forum thread from December 2019 that still shows `force force` enabled: https://www.carpenoctem.co/forums/m/26081621/viewthread/32974694-acre2-update-testing-report/post/138260285#p138260285

An ACRE2 mod update some time in 2020 reset the CBA settings to:

```
acre_sys_core_premixGlobalVolume = 1;
acre_sys_core_postmixGlobalVolume = 1;
```

most likely because at the time I didn't do the full cba comparison procedure as described in the [wiki here](https://github.com/CntoDev/cba-settings-lock/wiki/Updating-settings-on-modset-update), thus some default mod settings snuck back in.

My proposal is to set the values back to:

```
acre_sys_core_premixGlobalVolume = 1;
acre_sys_core_postmixGlobalVolume = 3;
```

to address the volume issues people describe in louder mods (JSRS, Star Wars etc.) but to NOT reintroduce `force force`, that way clients can still adjust the settings to their personal setups. However, the default volume baseline would be more appropriate with post-mix 3.0 as long as JSRS is in use.

**Note: this change would not affect any enforcement settings. It merely raises the baseline of the general voice volume. Players can still lower or raise that baseline on their own accord.**

**Comment by freghar** [comment]
I don't think you can change the default without enforcement.

https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System#setting-overwrite-cheat-sheet
```
Client overrides Mission, which overrides Server
```

**Comment by JamesTheClarke** [comment]
That is true, however it still can be beneficial to set a new default client value for two cases:

1.) new players who don't have a local profile setting yet (those get the one directed from the server)
2.) players who want to quickly load the "recommended" CNTO settings by pressing load server profile.
