### ISSUE TITLE
BFT Forced onto missions.

### ISSUE THREAD

**Issue by CNTODachi** [CntoDev/cba-settings-lock#4]
Hello,

The BFT setting was always optional so mission makers could create mission without map markers for certain scenarios, for example split up and lost then trying to find each other etc or guerrilla missions.

This is the setting below:
 
125 - // ACE Map
126 - force force ace_map_BFT_Enabled = true;

Could we allow mission makers this option again.

I can see a possible issue with this though as the default setting is always off meaning that every time a mission maker will need to load the server setting for his mission then untick this option.

Is there any way of making this setting default enabled to avoid the above issue and give back this option to Mission Makers?

**Comment by CNTODachi** [comment]
New Setting should be:

force ace_map_BFT_Enabled = true;

This will enable mission makers to override the server BFT Default on setting for missions that specifically need map markers turned off.

**Comment by JamesTheClarke** [comment]
I'll look into the cba-settings-lock on the server and adjust it accordingly.

**Comment by JamesTheClarke** [comment]
This issue has been resolved with the merger of the latest commit.
