### ISSUE TITLE
Lower ACRE2 AI Reveal Parameter

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/cba-settings-lock#64]
`force force acre_sys_core_revealToAI = 1;` (default value) currently allows for AI to hear players on volume level 3 beyond 100m according to @freghar 's tests. However, for gameplay reasons (avoiding crowding the radio net, making sure that they are heard by everyone etc.) leaders like FTLs usually run ACRE2 volume level 4 or even 5 - which means they tend to reveal themselves to AI from very far away.

Freghar suggested in a PM conversation to adjust the parameter to `0.08`.

_"It's on the more conservative side of things, to give a slight advantage to players (AI doesn't hear the faint distance voice a player would), but that equalizes at distances where AI will hear full shouting at ~ 100m. The default is pretty bad, default middle volume reveals even very far away (100+m)"_

I strongly agree with this suggestion and will put it on the agenda for the next Monthly Meeting as it does impact gameplay balance.

**Comment by freghar** [comment]
I suggested `0.08`, not `0.8`. Yes, the default is **that** wrong.

**Comment by JamesTheClarke** [comment]
Cheers for checking, was a typo on my part. Corrected the OP.

**Comment by JamesTheClarke** [comment]
Added topic to July Monthly Meeting Agenda: https://docs.google.com/document/d/1IS-9TGFGNkuK9sICTYDuFWpXnHxNdGbnJGx2_ECs4tU/

**Comment by JamesTheClarke** [comment]
SSgts unanimously agreed to accept the proposal by Freghar.
